language: ruby

cache: bundler 

before_install: gem update bundler

install:
  - bundle install

before_install:
- bash chmod +x ./setup.sh # will give proper permission

script:
  - "./setup.sh"

branches:
  only:
  - build

sudo: false